import pytest

from schieber.card import Card
from schieber.rules.suit import Suit
from schieber.players.challenge_player.strategy.mode.trumpf_color_mode import TrumpfColorMode


@pytest.mark.parametrize("suit, cards, score", [
    (Suit.ROSE,
     [Card(Suit.SCHELLE, 13), Card(Suit.SCHELLE, 12), Card(Suit.SCHELLE, 11), Card(Suit.SCHELLE, 8), Card(Suit.EICHEL, 12),
      Card(Suit.EICHEL, 11), Card(Suit.SCHILTE, 12), Card(Suit.SCHILTE, 7), Card(Suit.ROSE, 9)],
     15),
    (Suit.ROSE,
     [Card(Suit.SCHELLE, 14), Card(Suit.SCHELLE, 12), Card(Suit.SCHELLE, 9), Card(Suit.SCHELLE, 8), Card(Suit.SCHELLE, 6),
      Card(Suit.EICHEL, 11), Card(Suit.SCHILTE, 12), Card(Suit.SCHILTE, 7), Card(Suit.ROSE, 9)],
     19),
    (Suit.ROSE,
     [Card(Suit.SCHELLE, 14), Card(Suit.SCHELLE, 11), Card(Suit.SCHELLE, 9), Card(Suit.EICHEL, 12), Card(Suit.EICHEL, 6),
      Card(Suit.EICHEL, 7), Card(Suit.ROSE, 11), Card(Suit.ROSE, 7), Card(Suit.ROSE, 9)],
     59),
    (Suit.ROSE,
     [Card(Suit.SCHELLE, 11), Card(Suit.SCHELLE, 9), Card(Suit.SCHELLE, 6), Card(Suit.EICHEL, 14), Card(Suit.EICHEL, 12),
      Card(Suit.EICHEL, 7), Card(Suit.ROSE, 14), Card(Suit.ROSE, 7), Card(Suit.ROSE, 9)],
     41),
    (Suit.ROSE,
     [Card(Suit.SCHELLE, 14), Card(Suit.SCHELLE, 13), Card(Suit.SCHELLE, 12), Card(Suit.SCHELLE, 10), Card(Suit.SCHELLE, 6),
      Card(Suit.EICHEL, 7), Card(Suit.SCHILTE, 14), Card(Suit.ROSE, 13), Card(Suit.ROSE, 12)],
     36),
    (Suit.ROSE,
     [Card(Suit.SCHELLE, 6), Card(Suit.SCHELLE, 7), Card(Suit.SCHELLE, 8), Card(Suit.SCHELLE, 10), Card(Suit.EICHEL, 6),
      Card(Suit.EICHEL, 7), Card(Suit.SCHILTE, 14), Card(Suit.ROSE, 13), Card(Suit.ROSE, 12)],
     24),

    (Suit.SCHELLE,
     [Card(Suit.SCHELLE, 13), Card(Suit.SCHELLE, 12), Card(Suit.SCHELLE, 11), Card(Suit.SCHELLE, 8), Card(Suit.EICHEL, 12),
      Card(Suit.EICHEL, 11), Card(Suit.SCHILTE, 12), Card(Suit.SCHILTE, 7), Card(Suit.ROSE, 9)],
     60),
    (Suit.SCHELLE,
     [Card(Suit.SCHELLE, 14), Card(Suit.SCHELLE, 12), Card(Suit.SCHELLE, 9), Card(Suit.SCHELLE, 8), Card(Suit.SCHELLE, 6),
      Card(Suit.EICHEL, 11), Card(Suit.SCHILTE, 12), Card(Suit.SCHILTE, 7), Card(Suit.ROSE, 9)],
     57),
    (Suit.SCHELLE,
     [Card(Suit.SCHELLE, 14), Card(Suit.SCHELLE, 11), Card(Suit.SCHELLE, 9), Card(Suit.EICHEL, 12), Card(Suit.EICHEL, 6),
      Card(Suit.EICHEL, 7), Card(Suit.SCHILTE, 12), Card(Suit.SCHILTE, 7), Card(Suit.ROSE, 9)],
     57),
    (Suit.SCHELLE,
     [Card(Suit.SCHELLE, 11), Card(Suit.SCHELLE, 9), Card(Suit.SCHELLE, 6), Card(Suit.EICHEL, 14), Card(Suit.EICHEL, 12),
      Card(Suit.EICHEL, 7), Card(Suit.SCHILTE, 14), Card(Suit.SCHILTE, 7), Card(Suit.ROSE, 9)],
     63),
    (Suit.SCHELLE,
     [Card(Suit.SCHELLE, 14), Card(Suit.SCHELLE, 13), Card(Suit.SCHELLE, 12), Card(Suit.SCHELLE, 10), Card(Suit.SCHELLE, 6),
      Card(Suit.EICHEL, 7), Card(Suit.SCHILTE, 14), Card(Suit.SCHILTE, 13), Card(Suit.ROSE, 12)],
     60),
    (Suit.SCHELLE,
     [Card(Suit.SCHELLE, 6), Card(Suit.SCHELLE, 7), Card(Suit.SCHELLE, 8), Card(Suit.SCHELLE, 10), Card(Suit.EICHEL, 6),
      Card(Suit.EICHEL, 7), Card(Suit.SCHILTE, 14), Card(Suit.ROSE, 13), Card(Suit.ROSE, 12)],
     44),

    (Suit.EICHEL,
     [Card(Suit.SCHELLE, 13), Card(Suit.SCHELLE, 12), Card(Suit.SCHELLE, 11), Card(Suit.SCHELLE, 8), Card(Suit.EICHEL, 12),
      Card(Suit.EICHEL, 11), Card(Suit.SCHILTE, 12), Card(Suit.SCHILTE, 7), Card(Suit.ROSE, 9)],
     40),
    (Suit.EICHEL,
     [Card(Suit.SCHELLE, 14), Card(Suit.SCHELLE, 12), Card(Suit.SCHELLE, 9), Card(Suit.SCHELLE, 8), Card(Suit.SCHELLE, 6),
      Card(Suit.EICHEL, 9), Card(Suit.SCHILTE, 12), Card(Suit.SCHILTE, 7), Card(Suit.EICHEL, 11)],
     49),
    (Suit.EICHEL,
     [Card(Suit.SCHELLE, 14), Card(Suit.SCHELLE, 12), Card(Suit.SCHELLE, 13), Card(Suit.ROSE, 12), Card(Suit.EICHEL, 6),
      Card(Suit.EICHEL, 12), Card(Suit.EICHEL, 14), Card(Suit.EICHEL, 13), Card(Suit.ROSE, 9)],
     54),
    (Suit.EICHEL,
     [Card(Suit.SCHELLE, 11), Card(Suit.SCHELLE, 9), Card(Suit.SCHELLE, 6), Card(Suit.EICHEL, 14), Card(Suit.EICHEL, 12),
      Card(Suit.EICHEL, 7), Card(Suit.SCHILTE, 14), Card(Suit.SCHILTE, 7), Card(Suit.ROSE, 9)],
     36),
    (Suit.EICHEL,
     [Card(Suit.SCHELLE, 14), Card(Suit.SCHELLE, 13), Card(Suit.SCHELLE, 12), Card(Suit.SCHELLE, 10), Card(Suit.SCHELLE, 6),
      Card(Suit.EICHEL, 7), Card(Suit.SCHILTE, 14), Card(Suit.ROSE, 13), Card(Suit.ROSE, 12)],
     26),
    (Suit.EICHEL,
     [Card(Suit.SCHELLE, 6), Card(Suit.SCHELLE, 7), Card(Suit.SCHELLE, 8), Card(Suit.SCHELLE, 10), Card(Suit.EICHEL, 6),
      Card(Suit.EICHEL, 7), Card(Suit.SCHILTE, 14), Card(Suit.ROSE, 13), Card(Suit.ROSE, 12)],
     24),

    (Suit.SCHILTE,
     [Card(Suit.SCHELLE, 13), Card(Suit.SCHELLE, 12), Card(Suit.SCHELLE, 11), Card(Suit.SCHELLE, 8), Card(Suit.EICHEL, 12),
      Card(Suit.EICHEL, 11), Card(Suit.SCHILTE, 12), Card(Suit.SCHILTE, 7), Card(Suit.ROSE, 9)],
     20),
    (Suit.SCHILTE,
     [Card(Suit.SCHELLE, 14), Card(Suit.SCHELLE, 12), Card(Suit.SCHELLE, 9), Card(Suit.SCHELLE, 8), Card(Suit.SCHELLE, 6),
      Card(Suit.EICHEL, 11), Card(Suit.SCHILTE, 12), Card(Suit.SCHILTE, 7), Card(Suit.ROSE, 9)],
     24),
    (Suit.SCHILTE,
     [Card(Suit.SCHELLE, 14), Card(Suit.SCHELLE, 11), Card(Suit.SCHELLE, 9), Card(Suit.EICHEL, 12), Card(Suit.EICHEL, 6),
      Card(Suit.EICHEL, 7), Card(Suit.SCHILTE, 11), Card(Suit.SCHILTE, 7), Card(Suit.ROSE, 9)],
     44),
    (Suit.SCHILTE,
     [Card(Suit.SCHELLE, 11), Card(Suit.SCHELLE, 9), Card(Suit.SCHELLE, 6), Card(Suit.EICHEL, 14), Card(Suit.EICHEL, 13),
      Card(Suit.EICHEL, 7), Card(Suit.SCHILTE, 14), Card(Suit.SCHILTE, 7), Card(Suit.ROSE, 9)],
     30),
    (Suit.SCHILTE,
     [Card(Suit.SCHELLE, 14), Card(Suit.SCHELLE, 13), Card(Suit.SCHELLE, 12), Card(Suit.SCHELLE, 10), Card(Suit.SCHELLE, 6),
      Card(Suit.EICHEL, 7), Card(Suit.SCHILTE, 11), Card(Suit.ROSE, 13), Card(Suit.ROSE, 12)],
     42),
    (Suit.SCHILTE,
     [Card(Suit.SCHELLE, 6), Card(Suit.SCHELLE, 7), Card(Suit.SCHELLE, 8), Card(Suit.SCHELLE, 10), Card(Suit.EICHEL, 6),
      Card(Suit.EICHEL, 7), Card(Suit.SCHILTE, 14), Card(Suit.ROSE, 13), Card(Suit.ROSE, 12)],
     12),
])
def test_calculate_score_trumpf_colors(suit, cards, score):
    tcm = TrumpfColorMode(suit)
    s = tcm.calculate_mode_score(cards, geschoben=False)
    assert s == score


@pytest.mark.parametrize("suit, cards, highest, lowest", [
    (Suit.ROSE,
     [Card(Suit.SCHELLE, 13), Card(Suit.SCHELLE, 12), Card(Suit.SCHELLE, 11), Card(Suit.SCHELLE, 8), Card(Suit.EICHEL, 12),
      Card(Suit.EICHEL, 11), Card(Suit.SCHILTE, 12), Card(Suit.SCHILTE, 7), Card(Suit.ROSE, 9)],
     Card(Suit.ROSE, 9), Card(Suit.SCHILTE, 7)),
    (Suit.ROSE,
     [Card(Suit.SCHELLE, 14), Card(Suit.SCHELLE, 12), Card(Suit.SCHELLE, 9), Card(Suit.SCHELLE, 8), Card(Suit.SCHELLE, 6),
      Card(Suit.EICHEL, 11), Card(Suit.SCHILTE, 12), Card(Suit.SCHILTE, 7), Card(Suit.ROSE, 9)],
     Card(Suit.ROSE, 9), Card(Suit.SCHELLE, 6)),
    (Suit.ROSE,
     [Card(Suit.SCHELLE, 14), Card(Suit.SCHELLE, 11), Card(Suit.SCHELLE, 9), Card(Suit.EICHEL, 12), Card(Suit.EICHEL, 6),
      Card(Suit.EICHEL, 7), Card(Suit.ROSE, 11), Card(Suit.ROSE, 7), Card(Suit.ROSE, 9)],
     Card(Suit.ROSE, 11), Card(Suit.EICHEL, 6)),
    (Suit.ROSE,
     [Card(Suit.SCHELLE, 11), Card(Suit.SCHELLE, 9), Card(Suit.SCHELLE, 6), Card(Suit.EICHEL, 14), Card(Suit.EICHEL, 12),
      Card(Suit.EICHEL, 7), Card(Suit.ROSE, 14), Card(Suit.ROSE, 7), Card(Suit.ROSE, 9)],
     Card(Suit.ROSE, 9), Card(Suit.SCHELLE, 6)),
    (Suit.ROSE,
     [Card(Suit.SCHELLE, 14), Card(Suit.SCHELLE, 13), Card(Suit.SCHELLE, 12), Card(Suit.SCHELLE, 10), Card(Suit.SCHELLE, 6),
      Card(Suit.EICHEL, 7), Card(Suit.SCHILTE, 14), Card(Suit.ROSE, 13), Card(Suit.ROSE, 12)],
     Card(Suit.ROSE, 13), Card(Suit.SCHELLE, 6)),
    (Suit.ROSE,
     [Card(Suit.SCHELLE, 6), Card(Suit.SCHELLE, 7), Card(Suit.SCHELLE, 8), Card(Suit.SCHELLE, 10), Card(Suit.EICHEL, 8),
      Card(Suit.EICHEL, 7), Card(Suit.SCHILTE, 14), Card(Suit.ROSE, 13), Card(Suit.ROSE, 12)],
     Card(Suit.ROSE, 13), Card(Suit.SCHELLE, 6)),
])
def test_sort_by_rank_trumpf_colors(suit, cards, lowest, highest):
    tcm = TrumpfColorMode(suit)
    sorted = tcm.sort_by_rank(cards)
    assert sorted[-1] == lowest and sorted[0] == highest


@pytest.mark.parametrize("suit, cards, has_only_jack", [
    (Suit.ROSE,
     [Card(Suit.SCHELLE, 13), Card(Suit.SCHELLE, 12), Card(Suit.SCHELLE, 11), Card(Suit.SCHELLE, 8), Card(Suit.EICHEL, 12),
      Card(Suit.EICHEL, 11), Card(Suit.SCHILTE, 12), Card(Suit.SCHILTE, 7), Card(Suit.SCHILTE, 9)],
     False),
    (Suit.ROSE,
     [Card(Suit.SCHELLE, 14), Card(Suit.SCHELLE, 12), Card(Suit.SCHELLE, 9), Card(Suit.SCHELLE, 8), Card(Suit.SCHELLE, 6),
      Card(Suit.ROSE, 11), Card(Suit.SCHILTE, 12), Card(Suit.SCHILTE, 7), Card(Suit.SCHILTE, 9)],
     True),
    (Suit.ROSE,
     [Card(Suit.SCHELLE, 14), Card(Suit.SCHELLE, 11), Card(Suit.SCHELLE, 9), Card(Suit.EICHEL, 12), Card(Suit.EICHEL, 6),
      Card(Suit.EICHEL, 7), Card(Suit.ROSE, 11), Card(Suit.ROSE, 7), Card(Suit.ROSE, 9)],
     False),
])
def test_has_only_jack_trumpf_colors(suit, cards, has_only_jack):
    tcm = TrumpfColorMode(suit)
    assert has_only_jack == tcm.has_only_jack_of_trumpf(cards)
